name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 7 * * 1" # every Monday at 7am UTC (after dev log)
  workflow_dispatch:

jobs:
  update-wakatime:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          COMMIT_BY_ME: "True"
          SHOW_LINES_OF_CODE: "True"
